/**
 * PR F1 — Title v2 99 Catalog Convergence / Readiness Registry.
 *
 * この module は **planning専用**。production runtime pathへは一切接続しない:
 *   - `./v2.ts`（public barrel）からexportしない
 *   - evaluator（v2-evaluator.ts / v2-pipeline.ts）から参照しない
 *   - production Bot（apps/bot/src）からimportしない
 *   - award pathへ接続しない
 *
 * `meigoku_title_v2_catalog_99_fullclear.xlsx`（正本sheet: Catalog_99_FINAL /
 * Summary / Source_Map / Collection_Review / FullClear_Manifest）の
 * `Catalog_99_FINAL` シートを機械的に転記したもの。値は言い換えず原文のまま
 * 保持する——`semanticSpec`/`blockerNotes`等はxlsxの原文そのもの。
 *
 * `provisionalKey` はまだ production immutable title key ではない。source /
 * threshold / scope が確定してから正式key化する（xlsx Summaryの契約）。
 * このPRでは released `BehaviorTitleDefinition`/`MetaTitleDefinition` を
 * 一切登録しない——`packages/core/src/titles/v2-catalog-readiness.ts` が
 * 別layerとして現repoとの突き合わせ（readiness audit）を行う。
 *
 * 詳細は `docs/titles-v2-catalog-readiness.md` と `docs/titles-v2-design.md`
 * の「F1 — Catalog Convergence」節を参照。
 */

/** xlsx Catalog_99_FINAL の1行 = 1候補概念。planning-onlyの型——runtime TitleDefinitionとは別物。 */
export interface TitleV2CatalogCandidate {
  readonly no: number;
  readonly themeNo: number;
  readonly theme: string;
  readonly displayName: string;

  /** production immutable keyではない。xlsxの「仮key」をそのまま保持する。 */
  readonly provisionalKey: string;

  readonly kind: "behavior" | "meta";

  readonly groupKey: string;
  readonly seriesKey: string | null;
  readonly stage: number | null;

  /** xlsx「意味仕様」列の原文。言い換えない。 */
  readonly semanticSpec: string;

  readonly scopeIntent: string;
  readonly primarySourceIntent: string;
  readonly sourceStatusOriginal: string;

  readonly collectionCredit: "COUNTABLE" | "NONCOUNT";
  readonly hidden: boolean;

  readonly roleDependency: "none" | "yes" | "context";

  readonly thresholdIntent: string;
  readonly productionReadinessOriginal: string;

  /** xlsx「Blocker / Notes」列の原文。空文字列はxlsx側が空セルだったことを示す。 */
  readonly blockerNotes: string;

  readonly fullClear: "REQUIRED" | "EXEMPT_META";
}

export const TITLE_V2_CATALOG_CANDIDATES: readonly TitleV2CatalogCandidate[] = [
  {
    no: 1,
    themeNo: 1,
    theme: "場を起こす",
    displayName: "火種",
    provisionalKey: "v2.vc_ignite.spark",
    kind: "behavior",
    groupKey: "vc_ignite",
    seriesKey: "vc_ignite",
    stage: 1,
    semanticSpec: "空の公開VCから始め、後から他者を迎えて有効な共在が成立する。",
    scopeIntent: "catalog",
    primarySourceIntent: "vc_empty_start_then_joined",
    sourceStatusOriginal: "既存Title source",
    collectionCredit: "COUNTABLE",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "構造固定",
    productionReadinessOriginal: "既存source中心",
    blockerNotes: "private/bot/短時間/untrustedを除外。",
    fullClear: "REQUIRED",
  },
  {
    no: 2,
    themeNo: 1,
    theme: "場を起こす",
    displayName: "また点けた",
    provisionalKey: "v2.vc_ignite.rekindled",
    kind: "behavior",
    groupKey: "vc_ignite",
    seriesKey: "vc_ignite",
    stage: 2,
    semanticSpec: "空の場から人を迎える出来事が、異なる複数日に繰り返される。",
    scopeIntent: "catalog",
    primarySourceIntent: "vc_empty_start_then_joined + active-day aggregate",
    sourceStatusOriginal: "拡張必要",
    collectionCredit: "COUNTABLE",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "分布TBD",
    productionReadinessOriginal: "derived追加",
    blockerNotes: "",
    fullClear: "REQUIRED",
  },
  {
    no: 3,
    themeNo: 1,
    theme: "場を起こす",
    displayName: "渡り火",
    provisionalKey: "v2.vc_ignite.spread",
    kind: "behavior",
    groupKey: "vc_ignite",
    seriesKey: "vc_ignite",
    stage: 3,
    semanticSpec: "空の場から迎えた相手が、同じ一人に偏らず複数の異なる人へ広がる。",
    scopeIntent: "catalog",
    primarySourceIntent: "vc_empty_start_then_joined + distinct-joined aggregate",
    sourceStatusOriginal: "拡張必要",
    collectionCredit: "COUNTABLE",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "分布TBD",
    productionReadinessOriginal: "derived追加",
    blockerNotes: "",
    fullClear: "REQUIRED",
  },
  {
    no: 4,
    themeNo: 1,
    theme: "場を起こす",
    displayName: "どこでも着火",
    provisionalKey: "v2.vc_ignite.anywhere",
    kind: "behavior",
    groupKey: "vc_ignite",
    seriesKey: "vc_ignite",
    stage: 4,
    semanticSpec: "複数の論理的な公開VC領域で、空の場から人を迎える。",
    scopeIntent: "catalog",
    primarySourceIntent: "vc_empty_start_then_joined + socialAreaKey",
    sourceStatusOriginal: "taxonomy/source拡張必要",
    collectionCredit: "COUNTABLE",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "分布TBD",
    productionReadinessOriginal: "derived追加",
    blockerNotes: "",
    fullClear: "REQUIRED",
  },
  {
    no: 5,
    themeNo: 1,
    theme: "場を起こす",
    displayName: "篝火",
    provisionalKey: "v2.vc_ignite.bonfire",
    kind: "behavior",
    groupKey: "vc_ignite",
    seriesKey: null,
    stage: null,
    semanticSpec: "自分が空の場から始めると、十分な試行数の中で人が集まる傾向が安定して現れる。",
    scopeIntent: "catalog",
    primarySourceIntent: "vc_ignite aggregate",
    sourceStatusOriginal: "新derived必要",
    collectionCredit: "NONCOUNT",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "分布TBD",
    productionReadinessOriginal: "derived追加",
    blockerNotes: "比率だけでなく最小試行数・複数期間を要求。",
    fullClear: "REQUIRED",
  },
  {
    no: 6,
    themeNo: 2,
    theme: "場を締める",
    displayName: "残り火",
    provisionalKey: "v2.vc_closer.ember",
    kind: "behavior",
    groupKey: "vc_closer",
    seriesKey: "vc_closer",
    stage: 1,
    semanticSpec: "複数人の公開VCから他者が抜け、本人だけが最後に残る。",
    scopeIntent: "catalog",
    primarySourceIntent: "vc_last_occupant",
    sourceStatusOriginal: "既存Title source",
    collectionCredit: "COUNTABLE",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "構造固定",
    productionReadinessOriginal: "既存source中心",
    blockerNotes: "computeLastOccupantの同秒0秒visit tie bug修正が先。",
    fullClear: "REQUIRED",
  },
  {
    no: 7,
    themeNo: 2,
    theme: "場を締める",
    displayName: "まだいる",
    provisionalKey: "v2.vc_closer.still_here",
    kind: "behavior",
    groupKey: "vc_closer",
    seriesKey: "vc_closer",
    stage: 2,
    semanticSpec: "最後に残る出来事が異なる複数日に繰り返される。",
    scopeIntent: "catalog",
    primarySourceIntent: "vc_last_occupant + active-day aggregate",
    sourceStatusOriginal: "拡張必要",
    collectionCredit: "NONCOUNT",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "分布TBD",
    productionReadinessOriginal: "derived追加",
    blockerNotes: "",
    fullClear: "REQUIRED",
  },
  {
    no: 8,
    themeNo: 2,
    theme: "場を締める",
    displayName: "見届け人",
    provisionalKey: "v2.vc_closer.witness",
    kind: "behavior",
    groupKey: "vc_closer",
    seriesKey: "vc_closer",
    stage: 3,
    semanticSpec: "複数の論理的な公開VCで最後に残る。",
    scopeIntent: "catalog",
    primarySourceIntent: "vc_last_occupant + socialAreaKey",
    sourceStatusOriginal: "taxonomy/source拡張必要",
    collectionCredit: "NONCOUNT",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "分布TBD",
    productionReadinessOriginal: "derived追加",
    blockerNotes: "",
    fullClear: "REQUIRED",
  },
  {
    no: 9,
    themeNo: 2,
    theme: "場を締める",
    displayName: "戸締まりよろしく",
    provisionalKey: "v2.vc_closer.lockup",
    kind: "behavior",
    groupKey: "vc_closer",
    seriesKey: "vc_closer",
    stage: 4,
    semanticSpec: "十分な日数・期間・場所にわたり、最後まで残る傾向が長期的に現れる。",
    scopeIntent: "catalog",
    primarySourceIntent: "vc_last_occupant aggregate",
    sourceStatusOriginal: "拡張必要",
    collectionCredit: "NONCOUNT",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "分布TBD",
    productionReadinessOriginal: "derived追加",
    blockerNotes: "",
    fullClear: "REQUIRED",
  },
  {
    no: 10,
    themeNo: 3,
    theme: "一対一型",
    displayName: "差し向かい",
    provisionalKey: "v2.vc_duo.face_to_face",
    kind: "behavior",
    groupKey: "vc_duo_style",
    seriesKey: "vc_duo_style",
    stage: 1,
    semanticSpec: "1対1の有効共在が複数日に成立する。",
    scopeIntent: "catalog",
    primarySourceIntent: "vc_group_size_seconds + active-day/share aggregates",
    sourceStatusOriginal: "既存sourceの拡張必要",
    collectionCredit: "COUNTABLE",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "分布TBD",
    productionReadinessOriginal: "derived追加",
    blockerNotes: "アイデンティティ型。completion必須にすると逆のスタイルまで演じる圧が生まれる。",
    fullClear: "REQUIRED",
  },
  {
    no: 11,
    themeNo: 3,
    theme: "一対一型",
    displayName: "サシの民",
    provisionalKey: "v2.vc_duo.duo_native",
    kind: "behavior",
    groupKey: "vc_duo_style",
    seriesKey: "vc_duo_style",
    stage: 2,
    semanticSpec: "十分な観測量の中で1対1の比率が高く安定する。",
    scopeIntent: "catalog",
    primarySourceIntent: "vc_group_size_seconds + active-day/share aggregates",
    sourceStatusOriginal: "既存sourceの拡張必要",
    collectionCredit: "COUNTABLE",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "分布TBD",
    productionReadinessOriginal: "derived追加",
    blockerNotes: "アイデンティティ型。completion必須にすると逆のスタイルまで演じる圧が生まれる。",
    fullClear: "REQUIRED",
  },
  {
    no: 12,
    themeNo: 3,
    theme: "一対一型",
    displayName: "二人でよくない？",
    provisionalKey: "v2.vc_duo.two_is_enough",
    kind: "behavior",
    groupKey: "vc_duo_style",
    seriesKey: "vc_duo_style",
    stage: 3,
    semanticSpec: "長期・十分な標本で1対1が代表的な交流スタイルとして安定する。",
    scopeIntent: "catalog",
    primarySourceIntent: "vc_group_size_seconds + active-day/share aggregates",
    sourceStatusOriginal: "既存sourceの拡張必要",
    collectionCredit: "COUNTABLE",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "分布TBD",
    productionReadinessOriginal: "derived追加",
    blockerNotes: "アイデンティティ型。completion必須にすると逆のスタイルまで演じる圧が生まれる。",
    fullClear: "REQUIRED",
  },
  {
    no: 13,
    themeNo: 4,
    theme: "少人数型",
    displayName: "小卓",
    provisionalKey: "v2.vc_small.small_table",
    kind: "behavior",
    groupKey: "vc_small_group_style",
    seriesKey: "vc_small_group_style",
    stage: 1,
    semanticSpec: "3〜4人の有効共在が複数日に成立する。",
    scopeIntent: "catalog",
    primarySourceIntent: "vc_group_size_seconds + active-day/share aggregates",
    sourceStatusOriginal: "既存sourceの拡張必要",
    collectionCredit: "COUNTABLE",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "分布TBD",
    productionReadinessOriginal: "derived追加",
    blockerNotes: "「いつもの輪」は同じ固定メンバーではなく人数帯の意味。",
    fullClear: "REQUIRED",
  },
  {
    no: 14,
    themeNo: 4,
    theme: "少人数型",
    displayName: "囲炉裏端",
    provisionalKey: "v2.vc_small.hearthside",
    kind: "behavior",
    groupKey: "vc_small_group_style",
    seriesKey: "vc_small_group_style",
    stage: 2,
    semanticSpec: "十分な観測量の中で少人数帯の比率が高く安定する。",
    scopeIntent: "catalog",
    primarySourceIntent: "vc_group_size_seconds + active-day/share aggregates",
    sourceStatusOriginal: "既存sourceの拡張必要",
    collectionCredit: "COUNTABLE",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "分布TBD",
    productionReadinessOriginal: "derived追加",
    blockerNotes: "「いつもの輪」は同じ固定メンバーではなく人数帯の意味。",
    fullClear: "REQUIRED",
  },
  {
    no: 15,
    themeNo: 4,
    theme: "少人数型",
    displayName: "いつもの輪",
    provisionalKey: "v2.vc_small.usual_circle",
    kind: "behavior",
    groupKey: "vc_small_group_style",
    seriesKey: "vc_small_group_style",
    stage: 3,
    semanticSpec: "長期・十分な標本で少人数帯が代表的な交流スタイルとして安定する。",
    scopeIntent: "catalog",
    primarySourceIntent: "vc_group_size_seconds + active-day/share aggregates",
    sourceStatusOriginal: "既存sourceの拡張必要",
    collectionCredit: "COUNTABLE",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "分布TBD",
    productionReadinessOriginal: "derived追加",
    blockerNotes: "「いつもの輪」は同じ固定メンバーではなく人数帯の意味。",
    fullClear: "REQUIRED",
  },
  {
    no: 16,
    themeNo: 5,
    theme: "大人数型",
    displayName: "宴入り",
    provisionalKey: "v2.vc_large.party_entry",
    kind: "behavior",
    groupKey: "vc_large_group_style",
    seriesKey: "vc_large_group_style",
    stage: 1,
    semanticSpec: "5人以上の有効共在が複数日に成立する。",
    scopeIntent: "catalog",
    primarySourceIntent: "vc_group_size_seconds + active-day/share aggregates",
    sourceStatusOriginal: "既存sourceの拡張必要",
    collectionCredit: "COUNTABLE",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "分布TBD",
    productionReadinessOriginal: "derived追加",
    blockerNotes: "人気・主催力ではなく『いる人数帯』のスタイル。",
    fullClear: "REQUIRED",
  },
  {
    no: 17,
    themeNo: 5,
    theme: "大人数型",
    displayName: "人混み適性A",
    provisionalKey: "v2.vc_large.crowd_aptitude_a",
    kind: "behavior",
    groupKey: "vc_large_group_style",
    seriesKey: "vc_large_group_style",
    stage: 2,
    semanticSpec: "十分な観測量の中で大人数帯の比率が高く安定する。",
    scopeIntent: "catalog",
    primarySourceIntent: "vc_group_size_seconds + active-day/share aggregates",
    sourceStatusOriginal: "既存sourceの拡張必要",
    collectionCredit: "COUNTABLE",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "分布TBD",
    productionReadinessOriginal: "derived追加",
    blockerNotes: "人気・主催力ではなく『いる人数帯』のスタイル。",
    fullClear: "REQUIRED",
  },
  {
    no: 18,
    themeNo: 5,
    theme: "大人数型",
    displayName: "宴の華",
    provisionalKey: "v2.vc_large.party_flower",
    kind: "behavior",
    groupKey: "vc_large_group_style",
    seriesKey: "vc_large_group_style",
    stage: 3,
    semanticSpec: "長期・十分な標本で大人数帯が代表的な交流スタイルとして安定する。",
    scopeIntent: "catalog",
    primarySourceIntent: "vc_group_size_seconds + active-day/share aggregates",
    sourceStatusOriginal: "既存sourceの拡張必要",
    collectionCredit: "COUNTABLE",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "分布TBD",
    productionReadinessOriginal: "derived追加",
    blockerNotes: "人気・主催力ではなく『いる人数帯』のスタイル。",
    fullClear: "REQUIRED",
  },
  {
    no: 19,
    themeNo: 6,
    theme: "万能型",
    displayName: "両極端",
    provisionalKey: "v2.vc_flexible.both_extremes",
    kind: "behavior",
    groupKey: "vc_flexible_style",
    seriesKey: "vc_flexible_style",
    stage: 1,
    semanticSpec: "1対1と5人以上の双方に、複数日の有効共在がある。",
    scopeIntent: "catalog",
    primarySourceIntent: "vc_group_size_seconds + active-day/share aggregates",
    sourceStatusOriginal: "既存sourceの拡張必要",
    collectionCredit: "COUNTABLE",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "分布TBD",
    productionReadinessOriginal: "derived追加",
    blockerNotes: "スタイル型のためcompletion外推奨。",
    fullClear: "REQUIRED",
  },
  {
    no: 20,
    themeNo: 6,
    theme: "万能型",
    displayName: "人数不問",
    provisionalKey: "v2.vc_flexible.any_headcount",
    kind: "behavior",
    groupKey: "vc_flexible_style",
    seriesKey: "vc_flexible_style",
    stage: 2,
    semanticSpec: "1対1・3〜4人・5人以上の3帯すべてを複数日に経験する。",
    scopeIntent: "catalog",
    primarySourceIntent: "vc_group_size_seconds + active-day/share aggregates",
    sourceStatusOriginal: "既存sourceの拡張必要",
    collectionCredit: "COUNTABLE",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "分布TBD",
    productionReadinessOriginal: "derived追加",
    blockerNotes: "スタイル型のためcompletion外推奨。",
    fullClear: "REQUIRED",
  },
  {
    no: 21,
    themeNo: 6,
    theme: "万能型",
    displayName: "万座自在",
    provisionalKey: "v2.vc_flexible.all_seats",
    kind: "behavior",
    groupKey: "vc_flexible_style",
    seriesKey: "vc_flexible_style",
    stage: 3,
    semanticSpec: "3帯すべてを長期に使い、どれか一帯だけへ極端に偏らない。",
    scopeIntent: "catalog",
    primarySourceIntent: "vc_group_size_seconds + active-day/share aggregates",
    sourceStatusOriginal: "既存sourceの拡張必要",
    collectionCredit: "COUNTABLE",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "分布TBD",
    productionReadinessOriginal: "derived追加",
    blockerNotes: "スタイル型のためcompletion外推奨。",
    fullClear: "REQUIRED",
  },
  {
    no: 22,
    themeNo: 7,
    theme: "広い交友",
    displayName: "顔馴染み",
    provisionalKey: "v2.social_breadth.familiar_faces",
    kind: "behavior",
    groupKey: "social_breadth",
    seriesKey: "social_breadth",
    stage: 1,
    semanticSpec: "複数の異なる相手と、公開の有効共在が成立する。",
    scopeIntent: "catalog",
    primarySourceIntent: "vc_social_safe + distinct-counterpart aggregates",
    sourceStatusOriginal: "既存sourceの拡張必要",
    collectionCredit: "COUNTABLE",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "分布TBD",
    productionReadinessOriginal: "derived追加",
    blockerNotes: "",
    fullClear: "REQUIRED",
  },
  {
    no: 23,
    themeNo: 7,
    theme: "広い交友",
    displayName: "顔広くない？",
    provisionalKey: "v2.social_breadth.wide_circle",
    kind: "behavior",
    groupKey: "social_breadth",
    seriesKey: "social_breadth",
    stage: 2,
    semanticSpec: "より広い異なる相手との交流が、複数日に広がる。",
    scopeIntent: "catalog",
    primarySourceIntent: "vc_social_safe + distinct-counterpart aggregates",
    sourceStatusOriginal: "既存sourceの拡張必要",
    collectionCredit: "COUNTABLE",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "分布TBD",
    productionReadinessOriginal: "derived追加",
    blockerNotes: "",
    fullClear: "REQUIRED",
  },
  {
    no: 24,
    themeNo: 7,
    theme: "広い交友",
    displayName: "顔役",
    provisionalKey: "v2.social_breadth.known_face",
    kind: "behavior",
    groupKey: "social_breadth",
    seriesKey: "social_breadth",
    stage: 3,
    semanticSpec: "十分な期間にわたり、多くの異なる相手との交流が続く。",
    scopeIntent: "catalog",
    primarySourceIntent: "vc_social_safe + distinct-counterpart aggregates",
    sourceStatusOriginal: "既存sourceの拡張必要",
    collectionCredit: "COUNTABLE",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "分布TBD",
    productionReadinessOriginal: "derived追加",
    blockerNotes: "",
    fullClear: "REQUIRED",
  },
  {
    no: 25,
    themeNo: 7,
    theme: "広い交友",
    displayName: "お前誰を知らないの？",
    provisionalKey: "v2.social_breadth.who_dont_you_know",
    kind: "behavior",
    groupKey: "social_breadth",
    seriesKey: "social_breadth",
    stage: 4,
    semanticSpec: "長期・多数日にわたり非常に広い対人接点を持つ。",
    scopeIntent: "catalog",
    primarySourceIntent: "vc_social_safe + distinct-counterpart aggregates",
    sourceStatusOriginal: "既存sourceの拡張必要",
    collectionCredit: "COUNTABLE",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "分布TBD",
    productionReadinessOriginal: "derived追加",
    blockerNotes: "",
    fullClear: "REQUIRED",
  },
  {
    no: 26,
    themeNo: 7,
    theme: "広い交友",
    displayName: "垣根なし",
    provisionalKey: "v2.social_breadth.no_barriers",
    kind: "behavior",
    groupKey: "social_breadth",
    seriesKey: null,
    stage: null,
    semanticSpec: "複数の公開階級カテゴリに属する異なる人々と有効交流する。",
    scopeIntent: "catalog",
    primarySourceIntent: "social interaction + class-at-interaction",
    sourceStatusOriginal: "class履歴/source不足",
    collectionCredit: "NONCOUNT",
    hidden: false,
    roleDependency: "context",
    thresholdIntent: "分布TBD",
    productionReadinessOriginal: "複合BLOCK",
    blockerNotes: "同一人物の階級変化で複数枠を埋めない。",
    fullClear: "REQUIRED",
  },
  {
    no: 27,
    themeNo: 7,
    theme: "広い交友",
    displayName: "全館顔パス",
    provisionalKey: "v2.social_breadth.all_access",
    kind: "behavior",
    groupKey: "social_breadth",
    seriesKey: null,
    stage: null,
    semanticSpec: "複数の公開部署role-familyに属する異なる人々と有効交流する。",
    scopeIntent: "catalog",
    primarySourceIntent: "social interaction + role-family-at-interaction",
    sourceStatusOriginal: "role-at-time不足",
    collectionCredit: "NONCOUNT",
    hidden: false,
    roleDependency: "context",
    thresholdIntent: "分布TBD",
    productionReadinessOriginal: "role履歴待ち",
    blockerNotes: "一人のmulti-role相手で複数familyを埋めない。",
    fullClear: "REQUIRED",
  },
  {
    no: 28,
    themeNo: 8,
    theme: "深い交友",
    displayName: "再縁",
    provisionalKey: "v2.relationship_depth.reunion",
    kind: "behavior",
    groupKey: "relationship_depth",
    seriesKey: "relationship_depth",
    stage: 1,
    semanticSpec: "同じ一人と、異なる複数日に再び有効交流する。",
    scopeIntent: "catalog",
    primarySourceIntent: "vc_relationship_safe (proposed)",
    sourceStatusOriginal: "新safe source必要",
    collectionCredit: "COUNTABLE",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "分布TBD",
    productionReadinessOriginal: "source追加",
    blockerNotes: "counterpart identityはrestricted resolver側。公開名表示は別途双方向consent。",
    fullClear: "REQUIRED",
  },
  {
    no: 29,
    themeNo: 8,
    theme: "深い交友",
    displayName: "深縁",
    provisionalKey: "v2.relationship_depth.deep_bond",
    kind: "behavior",
    groupKey: "relationship_depth",
    seriesKey: "relationship_depth",
    stage: 2,
    semanticSpec: "同じ一人について、複数日数と十分なtrusted overlapの両方が成立する。",
    scopeIntent: "catalog",
    primarySourceIntent: "vc_relationship_safe (proposed)",
    sourceStatusOriginal: "新safe source必要",
    collectionCredit: "COUNTABLE",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "分布TBD",
    productionReadinessOriginal: "source追加",
    blockerNotes: "counterpart identityはrestricted resolver側。公開名表示は別途双方向consent。",
    fullClear: "REQUIRED",
  },
  {
    no: 30,
    themeNo: 8,
    theme: "深い交友",
    displayName: "腐れ縁",
    provisionalKey: "v2.relationship_depth.old_tie",
    kind: "behavior",
    groupKey: "relationship_depth",
    seriesKey: "relationship_depth",
    stage: 3,
    semanticSpec: "同じ一人との交流が、離れた複数期間へ繰り返し現れる。",
    scopeIntent: "catalog",
    primarySourceIntent: "vc_relationship_safe (proposed)",
    sourceStatusOriginal: "新safe source必要",
    collectionCredit: "COUNTABLE",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "分布TBD",
    productionReadinessOriginal: "source追加",
    blockerNotes: "counterpart identityはrestricted resolver側。公開名表示は別途双方向consent。",
    fullClear: "REQUIRED",
  },
  {
    no: 31,
    themeNo: 8,
    theme: "深い交友",
    displayName: "宿縁",
    provisionalKey: "v2.relationship_depth.destined_tie",
    kind: "behavior",
    groupKey: "relationship_depth",
    seriesKey: "relationship_depth",
    stage: 4,
    semanticSpec: "同じ一人との関係が長いfirst→last span・多数日・複数期間で続く。",
    scopeIntent: "catalog",
    primarySourceIntent: "vc_relationship_safe (proposed)",
    sourceStatusOriginal: "新safe source必要",
    collectionCredit: "COUNTABLE",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "分布TBD",
    productionReadinessOriginal: "source追加",
    blockerNotes: "counterpart identityはrestricted resolver側。公開名表示は別途双方向consent。",
    fullClear: "REQUIRED",
  },
  {
    no: 32,
    themeNo: 9,
    theme: "時間帯・生活痕",
    displayName: "朝番",
    provisionalKey: "v2.activity_time.morning_shift",
    kind: "behavior",
    groupKey: "activity_time",
    seriesKey: null,
    stage: null,
    semanticSpec: "朝の公開social activityが複数日に現れ、本人の活動分布でも一定程度目立つ。",
    scopeIntent: "catalog",
    primarySourceIntent: "social_activity_time_safe (TC+VC)",
    sourceStatusOriginal: "TC social source不足",
    collectionCredit: "NONCOUNT",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "分布TBD",
    productionReadinessOriginal: "基盤不足",
    blockerNotes: "BUMP/送金/賭場click等はsocial presenceとして数えない。",
    fullClear: "REQUIRED",
  },
  {
    no: 33,
    themeNo: 9,
    theme: "時間帯・生活痕",
    displayName: "昼下がり",
    provisionalKey: "v2.activity_time.afternoon",
    kind: "behavior",
    groupKey: "activity_time",
    seriesKey: null,
    stage: null,
    semanticSpec: "昼〜午後の公開social activityが複数日に現れ、活動分布でも一定程度目立つ。",
    scopeIntent: "catalog",
    primarySourceIntent: "social_activity_time_safe (TC+VC)",
    sourceStatusOriginal: "TC social source不足",
    collectionCredit: "NONCOUNT",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "分布TBD",
    productionReadinessOriginal: "基盤不足",
    blockerNotes: "BUMP/送金/賭場click等はsocial presenceとして数えない。",
    fullClear: "REQUIRED",
  },
  {
    no: 34,
    themeNo: 9,
    theme: "時間帯・生活痕",
    displayName: "宵っ張り",
    provisionalKey: "v2.activity_time.evening_owl",
    kind: "behavior",
    groupKey: "activity_time",
    seriesKey: null,
    stage: null,
    semanticSpec: "夕方〜日付変更前の公開social activityが複数日に現れ、活動分布でも一定程度目立つ。",
    scopeIntent: "catalog",
    primarySourceIntent: "social_activity_time_safe (TC+VC)",
    sourceStatusOriginal: "TC social source不足",
    collectionCredit: "NONCOUNT",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "分布TBD",
    productionReadinessOriginal: "基盤不足",
    blockerNotes: "BUMP/送金/賭場click等はsocial presenceとして数えない。",
    fullClear: "REQUIRED",
  },
  {
    no: 35,
    themeNo: 9,
    theme: "時間帯・生活痕",
    displayName: "深夜営業",
    provisionalKey: "v2.activity_time.late_night",
    kind: "behavior",
    groupKey: "activity_time",
    seriesKey: null,
    stage: null,
    semanticSpec: "日付変更後〜早朝の公開social activityが複数日に現れ、活動分布でも一定程度目立つ。",
    scopeIntent: "catalog",
    primarySourceIntent: "social_activity_time_safe (TC+VC)",
    sourceStatusOriginal: "TC social source不足",
    collectionCredit: "NONCOUNT",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "分布TBD",
    productionReadinessOriginal: "基盤不足",
    blockerNotes: "BUMP/送金/賭場click等はsocial presenceとして数えない。",
    fullClear: "REQUIRED",
  },
  {
    no: 36,
    themeNo: 9,
    theme: "時間帯・生活痕",
    displayName: "いつもの時間",
    provisionalKey: "v2.activity_time.usual_time",
    kind: "behavior",
    groupKey: "activity_time",
    seriesKey: null,
    stage: null,
    semanticSpec: "十分な期間で、活動開始・主要活動時刻が似たJST時間帯へ安定して集まる。",
    scopeIntent: "catalog",
    primarySourceIntent: "social_activity_time_safe (TC+VC)",
    sourceStatusOriginal: "TC social source不足",
    collectionCredit: "NONCOUNT",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "分布TBD",
    productionReadinessOriginal: "基盤不足",
    blockerNotes: "BUMP/送金/賭場click等はsocial presenceとして数えない。",
    fullClear: "REQUIRED",
  },
  {
    no: 37,
    themeNo: 9,
    theme: "時間帯・生活痕",
    displayName: "いつ寝てるの？",
    provisionalKey: "v2.activity_time.when_do_you_sleep",
    kind: "behavior",
    groupKey: "activity_time",
    seriesKey: null,
    stage: null,
    semanticSpec: "複数のdaypartに活動痕が多数日に分散し、一晩の徹夜では説明できない。",
    scopeIntent: "catalog",
    primarySourceIntent: "social_activity_time_safe (TC+VC)",
    sourceStatusOriginal: "TC social source不足",
    collectionCredit: "NONCOUNT",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "分布TBD",
    productionReadinessOriginal: "基盤不足",
    blockerNotes: "BUMP/送金/賭場click等はsocial presenceとして数えない。",
    fullClear: "REQUIRED",
  },
  {
    no: 38,
    themeNo: 10,
    theme: "BUMP / 鐘",
    displayName: "初鐘",
    provisionalKey: "v2.bump.first_bell",
    kind: "behavior",
    groupKey: "bump_contribution",
    seriesKey: "bump_contribution",
    stage: 1,
    semanticSpec: "catalog開始後、最初のeligible BUMP成功。",
    scopeIntent: "catalog",
    primarySourceIntent: "bump_events",
    sourceStatusOriginal: "既存Title source",
    collectionCredit: "COUNTABLE",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "構造固定",
    productionReadinessOriginal: "既存source中心",
    blockerNotes: "連続日streakは要求しない。同日複数回は強くdedupe。",
    fullClear: "REQUIRED",
  },
  {
    no: 39,
    themeNo: 10,
    theme: "BUMP / 鐘",
    displayName: "鐘撞き",
    provisionalKey: "v2.bump.bell_ringer",
    kind: "behavior",
    groupKey: "bump_contribution",
    seriesKey: "bump_contribution",
    stage: 2,
    semanticSpec: "BUMP成功が異なる多数日に広がる。",
    scopeIntent: "catalog",
    primarySourceIntent: "bump_events",
    sourceStatusOriginal: "既存Title source",
    collectionCredit: "COUNTABLE",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "分布TBD",
    productionReadinessOriginal: "既存source中心",
    blockerNotes: "連続日streakは要求しない。同日複数回は強くdedupe。",
    fullClear: "REQUIRED",
  },
  {
    no: 40,
    themeNo: 10,
    theme: "BUMP / 鐘",
    displayName: "鐘楼守",
    provisionalKey: "v2.bump.bell_tower_keeper",
    kind: "behavior",
    groupKey: "bump_contribution",
    seriesKey: "bump_contribution",
    stage: 3,
    semanticSpec: "BUMP成功が複数週/月・十分なspanへ繰り返し現れる。",
    scopeIntent: "catalog",
    primarySourceIntent: "bump_events",
    sourceStatusOriginal: "既存Title source",
    collectionCredit: "NONCOUNT",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "分布TBD",
    productionReadinessOriginal: "既存source中心",
    blockerNotes: "連続日streakは要求しない。同日複数回は強くdedupe。",
    fullClear: "REQUIRED",
  },
  {
    no: 41,
    themeNo: 10,
    theme: "BUMP / 鐘",
    displayName: "城の鐘",
    provisionalKey: "v2.bump.castle_bell",
    kind: "behavior",
    groupKey: "bump_contribution",
    seriesKey: "bump_contribution",
    stage: 4,
    semanticSpec: "長期間・多数日・複数期間にわたる安定したBUMP貢献。",
    scopeIntent: "catalog",
    primarySourceIntent: "bump_events",
    sourceStatusOriginal: "既存Title source",
    collectionCredit: "NONCOUNT",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "分布TBD",
    productionReadinessOriginal: "既存source中心",
    blockerNotes: "連続日streakは要求しない。同日複数回は強くdedupe。",
    fullClear: "REQUIRED",
  },
  {
    no: 42,
    themeNo: 11,
    theme: "TC交流",
    displayName: "第一声",
    provisionalKey: "v2.tc.first_voice",
    kind: "behavior",
    groupKey: "tc_start",
    seriesKey: null,
    stage: null,
    semanticSpec: "静かな公開TCへ新しいトップレベル発言を出し、他者が同じ会話を続ける。",
    scopeIntent: "catalog",
    primarySourceIntent: "tc_conversation_safe",
    sourceStatusOriginal: "TC canonical source不足",
    collectionCredit: "COUNTABLE",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "分布TBD",
    productionReadinessOriginal: "基盤不足",
    blockerNotes: "message内容のAI判定やraw message countは使わない。",
    fullClear: "REQUIRED",
  },
  {
    no: 43,
    themeNo: 11,
    theme: "TC交流",
    displayName: "会話、再開",
    provisionalKey: "v2.tc.conversation_resumed",
    kind: "behavior",
    groupKey: "tc_revive",
    seriesKey: "tc_revive",
    stage: 1,
    semanticSpec: "休眠していた既存会話へ投稿し、その後に他者が続きを返す。",
    scopeIntent: "catalog",
    primarySourceIntent: "tc_conversation_safe",
    sourceStatusOriginal: "TC canonical source不足",
    collectionCredit: "COUNTABLE",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "分布TBD",
    productionReadinessOriginal: "基盤不足",
    blockerNotes: "message内容のAI判定やraw message countは使わない。",
    fullClear: "REQUIRED",
  },
  {
    no: 44,
    themeNo: 11,
    theme: "TC交流",
    displayName: "蘇生職人",
    provisionalKey: "v2.tc.revivalist",
    kind: "behavior",
    groupKey: "tc_revive",
    seriesKey: "tc_revive",
    stage: 2,
    semanticSpec: "異なる会話・複数日にわたり、休眠会話を再開させる。",
    scopeIntent: "catalog",
    primarySourceIntent: "tc_conversation_safe",
    sourceStatusOriginal: "TC canonical source不足",
    collectionCredit: "COUNTABLE",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "分布TBD",
    productionReadinessOriginal: "基盤不足",
    blockerNotes: "message内容のAI判定やraw message countは使わない。",
    fullClear: "REQUIRED",
  },
  {
    no: 45,
    themeNo: 11,
    theme: "TC交流",
    displayName: "渡り筆",
    provisionalKey: "v2.tc.wandering_pen",
    kind: "behavior",
    groupKey: "tc_breadth",
    seriesKey: null,
    stage: null,
    semanticSpec: "複数の論理的な公開TC領域で有効交流する。",
    scopeIntent: "catalog",
    primarySourceIntent: "tc_conversation_safe + tcAreaKey",
    sourceStatusOriginal: "TC canonical source不足",
    collectionCredit: "COUNTABLE",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "分布TBD",
    productionReadinessOriginal: "基盤不足",
    blockerNotes: "message内容のAI判定やraw message countは使わない。",
    fullClear: "REQUIRED",
  },
  {
    no: 46,
    themeNo: 11,
    theme: "TC交流",
    displayName: "刺さったらしい",
    provisionalKey: "v2.tc.apparently_landed",
    kind: "behavior",
    groupKey: "tc_reaction",
    seriesKey: null,
    stage: null,
    semanticSpec: "複数の異なる投稿が、複数日・複数人から自然なreactionを受ける。",
    scopeIntent: "catalog",
    primarySourceIntent: "tc_reaction_safe",
    sourceStatusOriginal: "TC canonical source不足",
    collectionCredit: "NONCOUNT",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "分布TBD",
    productionReadinessOriginal: "基盤不足",
    blockerNotes: "message内容のAI判定やraw message countは使わない。",
    fullClear: "REQUIRED",
  },
  {
    no: 47,
    themeNo: 11,
    theme: "TC交流",
    displayName: "横から失礼",
    provisionalKey: "v2.tc.pardon_the_interruption",
    kind: "behavior",
    groupKey: "tc_join",
    seriesKey: null,
    stage: null,
    semanticSpec: "既に動いている複数人会話へ第三者として自然に入り、その後も会話が続く。",
    scopeIntent: "catalog",
    primarySourceIntent: "tc_conversation_safe",
    sourceStatusOriginal: "TC canonical source不足",
    collectionCredit: "NONCOUNT",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "分布TBD",
    productionReadinessOriginal: "基盤不足",
    blockerNotes: "message内容のAI判定やraw message countは使わない。",
    fullClear: "REQUIRED",
  },
  {
    no: 48,
    themeNo: 11,
    theme: "TC交流",
    displayName: "まだこの話してる",
    provisionalKey: "v2.tc.still_talking_about_this",
    kind: "behavior",
    groupKey: "tc_longlife",
    seriesKey: null,
    stage: null,
    semanticSpec: "自分が始めた会話・threadが複数人参加と離れた時間窓を越えて長く続く。",
    scopeIntent: "catalog",
    primarySourceIntent: "tc_conversation_safe",
    sourceStatusOriginal: "TC canonical source不足",
    collectionCredit: "NONCOUNT",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "分布TBD",
    productionReadinessOriginal: "基盤不足",
    blockerNotes: "message内容のAI判定やraw message countは使わない。",
    fullClear: "REQUIRED",
  },
  {
    no: 49,
    themeNo: 11,
    theme: "TC交流",
    displayName: "声筆両道",
    provisionalKey: "v2.tc.voice_and_pen",
    kind: "behavior",
    groupKey: "cross_modal",
    seriesKey: null,
    stage: null,
    semanticSpec: "TCとVCの双方で、複数日に有効social activityを持つ。",
    scopeIntent: "catalog",
    primarySourceIntent: "tc_conversation_safe + vc_social_safe",
    sourceStatusOriginal: "TC canonical source不足",
    collectionCredit: "COUNTABLE",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "分布TBD",
    productionReadinessOriginal: "基盤不足",
    blockerNotes: "message内容のAI判定やraw message countは使わない。",
    fullClear: "REQUIRED",
  },
  {
    no: 50,
    themeNo: 12,
    theme: "公開部屋",
    displayName: "初客",
    provisionalKey: "v2.room.first_guest",
    kind: "behavior",
    groupKey: "room_host_reception",
    seriesKey: "room_host_reception",
    stage: 1,
    semanticSpec: "自分のeligible公開部屋へ、初めて有効な来客が成立する。",
    scopeIntent: "catalog",
    primarySourceIntent: "public_room_activity_safe",
    sourceStatusOriginal: "正本あり/source化",
    collectionCredit: "COUNTABLE",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "構造固定",
    productionReadinessOriginal: "正本あり/source化",
    blockerNotes: "部屋作成だけでは不可。",
    fullClear: "REQUIRED",
  },
  {
    no: 51,
    themeNo: 12,
    theme: "公開部屋",
    displayName: "大入り",
    provisionalKey: "v2.room.big_turnout",
    kind: "behavior",
    groupKey: "room_host_reception",
    seriesKey: null,
    stage: null,
    semanticSpec: "自分の公開部屋が、固定した意味ある同時人数まで自然に賑わう。",
    scopeIntent: "catalog",
    primarySourceIntent: "public_room_activity_safe",
    sourceStatusOriginal: "rooms+VC join必要",
    collectionCredit: "NONCOUNT",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "分布TBD",
    productionReadinessOriginal: "正本あり/source化",
    blockerNotes: "literal capacity満員ではない。",
    fullClear: "REQUIRED",
  },
  {
    no: 52,
    themeNo: 12,
    theme: "公開部屋",
    displayName: "人気宿",
    provisionalKey: "v2.room.popular_inn",
    kind: "behavior",
    groupKey: "room_host_reception",
    seriesKey: "room_host_reception",
    stage: 2,
    semanticSpec: "異なる複数日・複数room sessionで、複数guestの有効来訪が繰り返される。",
    scopeIntent: "catalog",
    primarySourceIntent: "public_room_activity_safe",
    sourceStatusOriginal: "rooms+VC join必要",
    collectionCredit: "NONCOUNT",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "分布TBD",
    productionReadinessOriginal: "正本あり/source化",
    blockerNotes: "一発の大人数ではなく反復来客。",
    fullClear: "REQUIRED",
  },
  {
    no: 53,
    themeNo: 12,
    theme: "公開部屋",
    displayName: "また来てる",
    provisionalKey: "v2.room.back_again",
    kind: "behavior",
    groupKey: "room_return",
    seriesKey: null,
    stage: null,
    semanticSpec: "同じguestが別日・別sessionに再び自分の公開部屋へ有効来訪する。",
    scopeIntent: "catalog",
    primarySourceIntent: "public_room_activity_safe",
    sourceStatusOriginal: "pair→safe aggregate必要",
    collectionCredit: "COUNTABLE",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "分布TBD",
    productionReadinessOriginal: "derived追加",
    blockerNotes: "guest IDはevaluatorへ渡さない。",
    fullClear: "REQUIRED",
  },
  {
    no: 54,
    themeNo: 12,
    theme: "公開部屋",
    displayName: "渡り客",
    provisionalKey: "v2.room.wandering_guest",
    kind: "behavior",
    groupKey: "room_guest",
    seriesKey: null,
    stage: null,
    semanticSpec: "異なる複数ownerの公開部屋へ、複数日に有効guest利用する。",
    scopeIntent: "catalog",
    primarySourceIntent: "public_room_activity_safe",
    sourceStatusOriginal: "rooms+VC join必要",
    collectionCredit: "COUNTABLE",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "分布TBD",
    productionReadinessOriginal: "正本あり/source化",
    blockerNotes: "",
    fullClear: "REQUIRED",
  },
  {
    no: 55,
    themeNo: 12,
    theme: "公開部屋",
    displayName: "行ったり来たり",
    provisionalKey: "v2.room.back_and_forth",
    kind: "behavior",
    groupKey: "room_host_guest",
    seriesKey: null,
    stage: null,
    semanticSpec: "hostとして来客を迎え、guestとして他人の部屋にも遊びに行く。",
    scopeIntent: "catalog",
    primarySourceIntent: "public_room_activity_safe",
    sourceStatusOriginal: "複合aggregate必要",
    collectionCredit: "COUNTABLE",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "分布TBD",
    productionReadinessOriginal: "derived追加",
    blockerNotes: "",
    fullClear: "REQUIRED",
  },
  {
    no: 56,
    themeNo: 12,
    theme: "公開部屋",
    displayName: "宿の主",
    provisionalKey: "v2.room.innkeeper",
    kind: "behavior",
    groupKey: "room_host_usage",
    seriesKey: null,
    stage: null,
    semanticSpec: "来客人気とは別に、自分の公開部屋を複数日に継続して実利用する。",
    scopeIntent: "catalog",
    primarySourceIntent: "rooms activated lifecycle",
    sourceStatusOriginal: "既存正本あり",
    collectionCredit: "COUNTABLE",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "分布TBD",
    productionReadinessOriginal: "正本あり/source化",
    blockerNotes: "",
    fullClear: "REQUIRED",
  },
  {
    no: 57,
    themeNo: 12,
    theme: "公開部屋",
    displayName: "泊まりに来ました",
    provisionalKey: "v2.room.staying_over",
    kind: "behavior",
    groupKey: "room_role_guest",
    seriesKey: null,
    stage: null,
    semanticSpec: "宿屋系role保持中に、他人の公開部屋へ普通のguestとして有効来訪する。",
    scopeIntent: "catalog",
    primarySourceIntent: "public_room_activity_safe + role-at-time",
    sourceStatusOriginal: "role-at-time不足",
    collectionCredit: "NONCOUNT",
    hidden: false,
    roleDependency: "yes",
    thresholdIntent: "構造固定",
    productionReadinessOriginal: "role履歴待ち",
    blockerNotes: "completion外。",
    fullClear: "REQUIRED",
  },
  {
    no: 58,
    themeNo: 13,
    theme: "Land・経済",
    displayName: "ほんの気持ち",
    provisionalKey: "v2.economy.small_gift",
    kind: "behavior",
    groupKey: "tip_giving",
    seriesKey: "tip_giving",
    stage: 1,
    semanticSpec: "別ユーザーへの最初の有効な通常tip。",
    scopeIntent: "catalog",
    primarySourceIntent: "economy_activity_safe / transactions",
    sourceStatusOriginal: "ledger正本あり",
    collectionCredit: "COUNTABLE",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "構造固定",
    productionReadinessOriginal: "正本あり/source化",
    blockerNotes: "reversal済取引は無効。",
    fullClear: "REQUIRED",
  },
  {
    no: 59,
    themeNo: 13,
    theme: "Land・経済",
    displayName: "気前良し",
    provisionalKey: "v2.economy.generous",
    kind: "behavior",
    groupKey: "tip_giving",
    seriesKey: "tip_giving",
    stage: 2,
    semanticSpec: "異なる複数人・複数日に通常tipを贈る。",
    scopeIntent: "catalog",
    primarySourceIntent: "economy_activity_safe / transactions",
    sourceStatusOriginal: "ledger正本あり",
    collectionCredit: "COUNTABLE",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "分布TBD",
    productionReadinessOriginal: "正本あり/source化",
    blockerNotes: "総額ランキングにしない。",
    fullClear: "REQUIRED",
  },
  {
    no: 60,
    themeNo: 13,
    theme: "Land・経済",
    displayName: "お返しです",
    provisionalKey: "v2.economy.returning_the_favor",
    kind: "behavior",
    groupKey: "economy_reciprocity",
    seriesKey: null,
    stage: null,
    semanticSpec: "以前Landをくれた同じ相手へ、別の機会にこちらからLandを渡す。",
    scopeIntent: "catalog",
    primarySourceIntent: "economy_relationship_safe",
    sourceStatusOriginal: "pair aggregate必要",
    collectionCredit: "COUNTABLE",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "分布TBD",
    productionReadinessOriginal: "derived追加",
    blockerNotes: "本当の借金とは断定しない。",
    fullClear: "REQUIRED",
  },
  {
    no: 61,
    themeNo: 13,
    theme: "Land・経済",
    displayName: "天下の回りもの",
    provisionalKey: "v2.economy.money_goes_around",
    kind: "behavior",
    groupKey: "economy_flow",
    seriesKey: null,
    stage: null,
    semanticSpec: "自然な経済流入と流出が複数相手・複数機能・複数日に循環する。",
    scopeIntent: "catalog",
    primarySourceIntent: "economy_activity_safe + semantic classifier",
    sourceStatusOriginal: "classifier必要",
    collectionCredit: "COUNTABLE",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "分布TBD",
    productionReadinessOriginal: "正本あり/source化",
    blockerNotes: "給与・報酬・罰金・賭場損益などを除外。",
    fullClear: "REQUIRED",
  },
  {
    no: 62,
    themeNo: 13,
    theme: "Land・経済",
    displayName: "目移り",
    provisionalKey: "v2.economy.spoiled_for_choice",
    kind: "behavior",
    groupKey: "shop_breadth",
    seriesKey: null,
    stage: null,
    semanticSpec: "異なる複数のeligible商館商品を正常購入する。",
    scopeIntent: "catalog",
    primarySourceIntent: "shop purchases",
    sourceStatusOriginal: "購入台帳あり",
    collectionCredit: "COUNTABLE",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "分布TBD",
    productionReadinessOriginal: "正本あり/source化",
    blockerNotes: "refunded/cancelled除外。",
    fullClear: "REQUIRED",
  },
  {
    no: 63,
    themeNo: 13,
    theme: "Land・経済",
    displayName: "経済を回しているだけです",
    provisionalKey: "v2.economy.just_circulating",
    kind: "behavior",
    groupKey: "economy_breadth",
    seriesKey: null,
    stage: null,
    semanticSpec: "複数の異なる経済機能familyを正常利用する。",
    scopeIntent: "catalog",
    primarySourceIntent: "economy_activity_safe + semantic classifier",
    sourceStatusOriginal: "classifier必要",
    collectionCredit: "COUNTABLE",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "manifest依存",
    productionReadinessOriginal: "正本あり/source化",
    blockerNotes: "type数ではなく意味family数。",
    fullClear: "REQUIRED",
  },
  {
    no: 64,
    themeNo: 13,
    theme: "Land・経済",
    displayName: "自腹です",
    provisionalKey: "v2.economy.out_of_pocket",
    kind: "behavior",
    groupKey: "economy_role",
    seriesKey: null,
    stage: null,
    semanticSpec: "経済系role保持中に、管理取引ではない本人の通常経済利用を行う。",
    scopeIntent: "catalog",
    primarySourceIntent: "economy_activity_safe + role-at-time",
    sourceStatusOriginal: "role-at-time不足",
    collectionCredit: "NONCOUNT",
    hidden: false,
    roleDependency: "yes",
    thresholdIntent: "構造固定",
    productionReadinessOriginal: "role履歴待ち",
    blockerNotes: "completion外。",
    fullClear: "REQUIRED",
  },
  {
    no: 65,
    themeNo: 13,
    theme: "Land・経済",
    displayName: "店員買い",
    provisionalKey: "v2.economy.staff_purchase",
    kind: "behavior",
    groupKey: "shop_role",
    seriesKey: null,
    stage: null,
    semanticSpec: "商館系role保持中に、本人が普通の客としてeligible商品を購入する。",
    scopeIntent: "catalog",
    primarySourceIntent: "shop purchases + role-at-time",
    sourceStatusOriginal: "role-at-time不足",
    collectionCredit: "NONCOUNT",
    hidden: false,
    roleDependency: "yes",
    thresholdIntent: "構造固定",
    productionReadinessOriginal: "role履歴待ち",
    blockerNotes: "completion外。",
    fullClear: "REQUIRED",
  },
  {
    no: 66,
    themeNo: 14,
    theme: "賭場",
    displayName: "初勝負",
    provisionalKey: "v2.casino.first_match",
    kind: "behavior",
    groupKey: "casino_breadth",
    seriesKey: "casino_breadth",
    stage: 1,
    semanticSpec: "第I期対象の賭場ゲームを初めて正常精算まで完了する。",
    scopeIntent: "catalog",
    primarySourceIntent: "casino_game_activity_safe",
    sourceStatusOriginal: "casino_game正本あり",
    collectionCredit: "NONCOUNT",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "構造固定",
    productionReadinessOriginal: "正本あり/source化",
    blockerNotes: "勝敗・賭け額は不問。",
    fullClear: "REQUIRED",
  },
  {
    no: 67,
    themeNo: 14,
    theme: "賭場",
    displayName: "つまみ食い",
    provisionalKey: "v2.casino.sampling",
    kind: "behavior",
    groupKey: "casino_breadth",
    seriesKey: "casino_breadth",
    stage: 2,
    semanticSpec: "異なる複数game familyを正常完了する。",
    scopeIntent: "catalog",
    primarySourceIntent: "casino_game_activity_safe",
    sourceStatusOriginal: "game event正本あり",
    collectionCredit: "NONCOUNT",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "分布TBD",
    productionReadinessOriginal: "正本あり/source化",
    blockerNotes: "",
    fullClear: "REQUIRED",
  },
  {
    no: 68,
    themeNo: 14,
    theme: "賭場",
    displayName: "賭場通",
    provisionalKey: "v2.casino.casino_regular",
    kind: "behavior",
    groupKey: "casino_breadth",
    seriesKey: "casino_breadth",
    stage: 3,
    semanticSpec: "幅広いgame familyを複数日に利用する。",
    scopeIntent: "catalog",
    primarySourceIntent: "casino_game_activity_safe",
    sourceStatusOriginal: "game event正本あり",
    collectionCredit: "NONCOUNT",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "分布TBD",
    productionReadinessOriginal: "正本あり/source化",
    blockerNotes: "",
    fullClear: "REQUIRED",
  },
  {
    no: 69,
    themeNo: 14,
    theme: "賭場",
    displayName: "何でもござれ",
    provisionalKey: "v2.casino.anything_goes",
    kind: "behavior",
    groupKey: "casino_breadth",
    seriesKey: "casino_breadth",
    stage: 4,
    semanticSpec: "第I期core game familyをすべて正常完了する。",
    scopeIntent: "catalog",
    primarySourceIntent: "casino_game_activity_safe",
    sourceStatusOriginal: "game registry必要",
    collectionCredit: "NONCOUNT",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "manifest依存",
    productionReadinessOriginal: "正本あり/source化",
    blockerNotes: "第I期は8 family想定。後発gameを旧editionへ追加しない。",
    fullClear: "REQUIRED",
  },
  {
    no: 70,
    themeNo: 14,
    theme: "賭場",
    displayName: "卓主",
    provisionalKey: "v2.casino.table_host",
    kind: "behavior",
    groupKey: "casino_table",
    seriesKey: "casino_table",
    stage: 1,
    semanticSpec: "自分が建てたeligible卓へ他者が来て有効滞在する。",
    scopeIntent: "catalog",
    primarySourceIntent: "casino_table_activity_safe",
    sourceStatusOriginal: "卓正本+VC join必要",
    collectionCredit: "NONCOUNT",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "構造固定",
    productionReadinessOriginal: "正本あり/source化",
    blockerNotes: "空卓大量生成では不可。",
    fullClear: "REQUIRED",
  },
  {
    no: 71,
    themeNo: 14,
    theme: "賭場",
    displayName: "繁盛卓",
    provisionalKey: "v2.casino.busy_table",
    kind: "behavior",
    groupKey: "casino_table",
    seriesKey: "casino_table",
    stage: 2,
    semanticSpec: "来客のある独立卓が複数日・複数guestへ繰り返される。",
    scopeIntent: "catalog",
    primarySourceIntent: "casino_table_activity_safe",
    sourceStatusOriginal: "卓正本+VC join必要",
    collectionCredit: "NONCOUNT",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "分布TBD",
    productionReadinessOriginal: "derived追加",
    blockerNotes: "",
    fullClear: "REQUIRED",
  },
  {
    no: 72,
    themeNo: 14,
    theme: "賭場",
    displayName: "当たるとは言ってない",
    provisionalKey: "v2.casino.never_said_id_win",
    kind: "behavior",
    groupKey: "casino_market",
    seriesKey: null,
    stage: null,
    semanticSpec: "他人のstandard予想板へ、複数回・複数日に正常参加する。",
    scopeIntent: "catalog",
    primarySourceIntent: "casino_market_activity_safe",
    sourceStatusOriginal: "market/bet正本あり",
    collectionCredit: "NONCOUNT",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "分布TBD",
    productionReadinessOriginal: "正本あり/source化",
    blockerNotes: "的中率・賭け額は見ない。",
    fullClear: "REQUIRED",
  },
  {
    no: 73,
    themeNo: 14,
    theme: "賭場",
    displayName: "今日は客です",
    provisionalKey: "v2.casino.customer_today",
    kind: "behavior",
    groupKey: "casino_role",
    seriesKey: null,
    stage: null,
    semanticSpec: "賭場系role保持中に、普通の客としてcore gameまたは他人のstandard板へ参加する。",
    scopeIntent: "catalog",
    primarySourceIntent: "casino activity + role-at-time",
    sourceStatusOriginal: "role-at-time不足",
    collectionCredit: "NONCOUNT",
    hidden: false,
    roleDependency: "yes",
    thresholdIntent: "構造固定",
    productionReadinessOriginal: "role履歴待ち",
    blockerNotes: "completion外。",
    fullClear: "REQUIRED",
  },
  {
    no: 74,
    themeNo: 15,
    theme: "招待",
    displayName: "種を蒔く",
    provisionalKey: "v2.invite.sow_seed",
    kind: "behavior",
    groupKey: "direct_invite",
    seriesKey: "direct_invite",
    stage: 1,
    semanticSpec: "自分のconfirmed direct inviteeが初めて入城まで到達する。",
    scopeIntent: "catalog",
    primarySourceIntent: "invite_network_safe / invites",
    sourceStatusOriginal: "confirmed invites正本あり",
    collectionCredit: "NONCOUNT",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "構造固定",
    productionReadinessOriginal: "正本あり/source化",
    blockerNotes: "招待人数コンプ圧を避けるためcompletion外。",
    fullClear: "REQUIRED",
  },
  {
    no: 75,
    themeNo: 15,
    theme: "招待",
    displayName: "また芽が出た",
    provisionalKey: "v2.invite.sprouted_again",
    kind: "behavior",
    groupKey: "direct_invite",
    seriesKey: "direct_invite",
    stage: 2,
    semanticSpec: "別のconfirmed direct inviteeも入城まで到達する。",
    scopeIntent: "catalog",
    primarySourceIntent: "invite_network_safe / invites",
    sourceStatusOriginal: "confirmed invites正本あり",
    collectionCredit: "NONCOUNT",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "分布TBD",
    productionReadinessOriginal: "正本あり/source化",
    blockerNotes: "",
    fullClear: "REQUIRED",
  },
  {
    no: 76,
    themeNo: 15,
    theme: "招待",
    displayName: "根付いた",
    provisionalKey: "v2.invite.took_root",
    kind: "behavior",
    groupKey: "invite_retention",
    seriesKey: null,
    stage: null,
    semanticSpec: "confirmed direct inviteeが、入城後も離れた複数日に公開活動を続ける。",
    scopeIntent: "catalog",
    primarySourceIntent: "invite_retention_safe",
    sourceStatusOriginal: "retention source不足",
    collectionCredit: "NONCOUNT",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "分布TBD",
    productionReadinessOriginal: "複合BLOCK",
    blockerNotes: "階級・評価は使わない。",
    fullClear: "REQUIRED",
  },
  {
    no: 77,
    themeNo: 15,
    theme: "招待",
    displayName: "枝分かれ",
    provisionalKey: "v2.invite.branching",
    kind: "behavior",
    groupKey: "invite_network",
    seriesKey: null,
    stage: null,
    semanticSpec: "根付いたdirect inviteeから、さらに次のconfirmed inviteが生まれる。",
    scopeIntent: "catalog",
    primarySourceIntent: "invite_network_safe + invite_retention_safe",
    sourceStatusOriginal: "retention source不足",
    collectionCredit: "NONCOUNT",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "構造+分布",
    productionReadinessOriginal: "複合BLOCK",
    blockerNotes: "",
    fullClear: "REQUIRED",
  },
  {
    no: 78,
    themeNo: 15,
    theme: "招待",
    displayName: "縁の森",
    provisionalKey: "v2.invite.forest_of_ties",
    kind: "behavior",
    groupKey: "invite_network",
    seriesKey: null,
    stage: null,
    semanticSpec: "複数の根付いたdirect branchが、それぞれ次世代へ独立して広がる。",
    scopeIntent: "catalog",
    primarySourceIntent: "invite_network_safe + invite_retention_safe",
    sourceStatusOriginal: "retention source不足",
    collectionCredit: "NONCOUNT",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "分布TBD",
    productionReadinessOriginal: "複合BLOCK",
    blockerNotes: "一本の長い鎖だけでは不可。",
    fullClear: "REQUIRED",
  },
  {
    no: 79,
    themeNo: 15,
    theme: "招待",
    displayName: "実家に帰る",
    provisionalKey: "v2.invite.back_home",
    kind: "behavior",
    groupKey: "invite_reunion",
    seriesKey: null,
    stage: null,
    semanticSpec: "direct inviteeと、入城日とは別の日に通常の公開活動で再び有効交流する。",
    scopeIntent: "catalog",
    primarySourceIntent: "invite_retention_safe + social source",
    sourceStatusOriginal: "social/retention join不足",
    collectionCredit: "NONCOUNT",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "分布TBD",
    productionReadinessOriginal: "複合BLOCK",
    blockerNotes: "相手名は公開しない。",
    fullClear: "REQUIRED",
  },
  {
    no: 80,
    themeNo: 16,
    theme: "イベント",
    displayName: "初陣",
    provisionalKey: "v2.event.first_event",
    kind: "behavior",
    groupKey: "event_attendance",
    seriesKey: "event_attendance",
    stage: 1,
    semanticSpec: "completed公式イベントへ、初めてconfirmed participantとして一般参加する。",
    scopeIntent: "catalog",
    primarySourceIntent: "official_events + event_involvements (proposed)",
    sourceStatusOriginal: "全イベント共通正本なし",
    collectionCredit: "NONCOUNT",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "構造固定",
    productionReadinessOriginal: "基盤不足",
    blockerNotes: "第I期completion外。参加証拠はイベントごとの自然な操作から取り、称号専用操作を強制しない。",
    fullClear: "REQUIRED",
  },
  {
    no: 81,
    themeNo: 16,
    theme: "イベント",
    displayName: "祭り巡り",
    provisionalKey: "v2.event.festival_hopper",
    kind: "behavior",
    groupKey: "event_attendance",
    seriesKey: "event_attendance",
    stage: 2,
    semanticSpec: "複数の異なるcompleted公式イベントへconfirmed participantとして参加する。",
    scopeIntent: "catalog",
    primarySourceIntent: "official_events + event_involvements (proposed)",
    sourceStatusOriginal: "全イベント共通正本なし",
    collectionCredit: "NONCOUNT",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "分布TBD",
    productionReadinessOriginal: "基盤不足",
    blockerNotes: "第I期completion外。参加証拠はイベントごとの自然な操作から取り、称号専用操作を強制しない。",
    fullClear: "REQUIRED",
  },
  {
    no: 82,
    themeNo: 16,
    theme: "イベント",
    displayName: "また来た",
    provisionalKey: "v2.event.back_again_event",
    kind: "behavior",
    groupKey: "event_continuity",
    seriesKey: null,
    stage: null,
    semanticSpec: "離れた暦期間にも公式イベント参加が繰り返される。",
    scopeIntent: "catalog",
    primarySourceIntent: "official_events + event_involvements (proposed)",
    sourceStatusOriginal: "全イベント共通正本なし",
    collectionCredit: "NONCOUNT",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "分布TBD",
    productionReadinessOriginal: "基盤不足",
    blockerNotes: "第I期completion外。参加証拠はイベントごとの自然な操作から取り、称号専用操作を強制しない。",
    fullClear: "REQUIRED",
  },
  {
    no: 83,
    themeNo: 16,
    theme: "イベント",
    displayName: "表も裏も",
    provisionalKey: "v2.event.both_sides",
    kind: "behavior",
    groupKey: "event_dual_role",
    seriesKey: null,
    stage: null,
    semanticSpec: "別イベントでparticipant側とstaff/organizer側の双方を経験する。",
    scopeIntent: "catalog",
    primarySourceIntent: "official_events + event_involvements (proposed)",
    sourceStatusOriginal: "全イベント共通正本なし",
    collectionCredit: "NONCOUNT",
    hidden: false,
    roleDependency: "yes",
    thresholdIntent: "構造固定",
    productionReadinessOriginal: "基盤不足",
    blockerNotes: "第I期completion外。参加証拠はイベントごとの自然な操作から取り、称号専用操作を強制しない。",
    fullClear: "REQUIRED",
  },
  {
    no: 84,
    themeNo: 16,
    theme: "イベント",
    displayName: "仕掛け人",
    provisionalKey: "v2.event.instigator",
    kind: "behavior",
    groupKey: "event_organizer",
    seriesKey: null,
    stage: null,
    semanticSpec: "primary organizerとして登録されたイベントを実際にcompletedまで成立させる。",
    scopeIntent: "catalog",
    primarySourceIntent: "official_events + event_involvements (proposed)",
    sourceStatusOriginal: "全イベント共通正本なし",
    collectionCredit: "NONCOUNT",
    hidden: false,
    roleDependency: "yes",
    thresholdIntent: "構造固定",
    productionReadinessOriginal: "基盤不足",
    blockerNotes: "第I期completion外。参加証拠はイベントごとの自然な操作から取り、称号専用操作を強制しない。",
    fullClear: "REQUIRED",
  },
  {
    no: 85,
    themeNo: 17,
    theme: "城横断",
    displayName: "味見",
    provisionalKey: "v2.castle.taste",
    kind: "behavior",
    groupKey: "castle_experience",
    seriesKey: "castle_experience",
    stage: 1,
    semanticSpec: "第I期manifestの異なる2領域で意味ある利用を成立させる。",
    scopeIntent: "catalog",
    primarySourceIntent: "castle_experience_safe",
    sourceStatusOriginal: "各source束ね必要",
    collectionCredit: "NONCOUNT",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "構造固定",
    productionReadinessOriginal: "複合BLOCK",
    blockerNotes: "第I期はevent familyを含むため、event infra完成までrelease不可。",
    fullClear: "REQUIRED",
  },
  {
    no: 86,
    themeNo: 17,
    theme: "城横断",
    displayName: "食べ歩き",
    provisionalKey: "v2.castle.food_walk",
    kind: "behavior",
    groupKey: "castle_experience",
    seriesKey: "castle_experience",
    stage: 2,
    semanticSpec: "第I期manifestの複数領域を巡る。",
    scopeIntent: "catalog",
    primarySourceIntent: "castle_experience_safe",
    sourceStatusOriginal: "各source束ね必要",
    collectionCredit: "NONCOUNT",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "manifest依存",
    productionReadinessOriginal: "複合BLOCK",
    blockerNotes: "",
    fullClear: "REQUIRED",
  },
  {
    no: 87,
    themeNo: 17,
    theme: "城横断",
    displayName: "雑食",
    provisionalKey: "v2.castle.omnivorous",
    kind: "behavior",
    groupKey: "castle_experience",
    seriesKey: "castle_experience",
    stage: 3,
    semanticSpec: "十分なfamily数に加え、交流・経済遊戯・城全体の各super-domainへ広がる。",
    scopeIntent: "catalog",
    primarySourceIntent: "castle_experience_safe",
    sourceStatusOriginal: "super-domain manifest必要",
    collectionCredit: "NONCOUNT",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "manifest依存",
    productionReadinessOriginal: "複合BLOCK",
    blockerNotes: "",
    fullClear: "REQUIRED",
  },
  {
    no: 88,
    themeNo: 17,
    theme: "城横断",
    displayName: "フルコース",
    provisionalKey: "v2.castle.full_course",
    kind: "behavior",
    groupKey: "castle_experience",
    seriesKey: "castle_experience",
    stage: 4,
    semanticSpec: "第I期manifestのほぼ全領域を有効利用する。",
    scopeIntent: "catalog",
    primarySourceIntent: "castle_experience_safe",
    sourceStatusOriginal: "manifest/source束ね必要",
    collectionCredit: "NONCOUNT",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "manifest依存",
    productionReadinessOriginal: "複合BLOCK",
    blockerNotes: "",
    fullClear: "REQUIRED",
  },
  {
    no: 89,
    themeNo: 17,
    theme: "城横断",
    displayName: "城喰らい",
    provisionalKey: "v2.castle.castle_eater",
    kind: "behavior",
    groupKey: "castle_experience",
    seriesKey: "castle_experience",
    stage: 5,
    semanticSpec: "第I期城横断manifestの全familyを有効利用する。",
    scopeIntent: "catalog",
    primarySourceIntent: "castle_experience_safe",
    sourceStatusOriginal: "manifest/source束ね必要",
    collectionCredit: "NONCOUNT",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "manifest固定",
    productionReadinessOriginal: "複合BLOCK",
    blockerNotes: "招待・役職・階級・評価はmanifest外。",
    fullClear: "REQUIRED",
  },
  {
    no: 90,
    themeNo: 17,
    theme: "城横断",
    displayName: "城勤め",
    provisionalKey: "v2.castle.castle_worker",
    kind: "behavior",
    groupKey: "castle_role",
    seriesKey: null,
    stage: null,
    semanticSpec: "eligible public role保持中に、担当内外を含む複数の通常領域で普通に遊ぶ。",
    scopeIntent: "catalog",
    primarySourceIntent: "castle_experience_safe + role-at-time",
    sourceStatusOriginal: "role-at-time不足",
    collectionCredit: "NONCOUNT",
    hidden: false,
    roleDependency: "yes",
    thresholdIntent: "分布TBD",
    productionReadinessOriginal: "role履歴待ち",
    blockerNotes: "completion外。",
    fullClear: "REQUIRED",
  },
  {
    no: 91,
    themeNo: 17,
    theme: "城横断",
    displayName: "勤務時間外",
    provisionalKey: "v2.castle.off_duty",
    kind: "behavior",
    groupKey: "castle_role",
    seriesKey: null,
    stage: null,
    semanticSpec: "eligible public role保持中、担当domain外の通常活動が複数日に反復する。",
    scopeIntent: "catalog",
    primarySourceIntent: "castle_experience_safe + role-at-time",
    sourceStatusOriginal: "role-at-time不足",
    collectionCredit: "NONCOUNT",
    hidden: false,
    roleDependency: "yes",
    thresholdIntent: "分布TBD",
    productionReadinessOriginal: "role履歴待ち",
    blockerNotes: "複数roleのassignedDomainsを合算してoutside判定。",
    fullClear: "REQUIRED",
  },
  {
    no: 92,
    themeNo: 18,
    theme: "収集・極め",
    displayName: "初印",
    provisionalKey: "v2.meta.first_mark",
    kind: "meta",
    groupKey: "collection_meta",
    seriesKey: "collection_meta",
    stage: 1,
    semanticSpec: "最初に取得した非meta印。通常・極・specialのどれでもよい。",
    scopeIntent: "catalog",
    primarySourceIntent: "title_awards",
    sourceStatusOriginal: "meta path未実装",
    collectionCredit: "NONCOUNT",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "構造固定",
    productionReadinessOriginal: "meta基盤待ち",
    blockerNotes: "meta自身はcollection/full-clearへ数えない。",
    fullClear: "EXEMPT_META",
  },
  {
    no: 93,
    themeNo: 18,
    theme: "収集・極め",
    displayName: "集め始めました",
    provisionalKey: "v2.meta.started_collecting",
    kind: "meta",
    groupKey: "collection_meta",
    seriesKey: "collection_meta",
    stage: 2,
    semanticSpec: "COUNTABLE印が一定数集まり、印録が形になり始める。",
    scopeIntent: "catalog",
    primarySourceIntent: "title_collection_state",
    sourceStatusOriginal: "meta path未実装",
    collectionCredit: "NONCOUNT",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "分布TBD",
    productionReadinessOriginal: "meta基盤待ち",
    blockerNotes: "閾値は取得分布を見て固定。",
    fullClear: "EXEMPT_META",
  },
  {
    no: 94,
    themeNo: 18,
    theme: "収集・極め",
    displayName: "蒐集癖",
    provisionalKey: "v2.meta.collector_habit",
    kind: "meta",
    groupKey: "collection_meta",
    seriesKey: "collection_meta",
    stage: 3,
    semanticSpec: "COUNTABLE印をかなり多く集める。",
    scopeIntent: "catalog",
    primarySourceIntent: "title_collection_state",
    sourceStatusOriginal: "meta path未実装",
    collectionCredit: "NONCOUNT",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "分布TBD",
    productionReadinessOriginal: "meta基盤待ち",
    blockerNotes: "単純%ではなく実データ分布から閾値を決める。",
    fullClear: "EXEMPT_META",
  },
  {
    no: 95,
    themeNo: 18,
    theme: "収集・極め",
    displayName: "まだ集めるの？",
    provisionalKey: "v2.meta.still_collecting",
    kind: "meta",
    groupKey: "collection_meta",
    seriesKey: "collection_meta",
    stage: 4,
    semanticSpec: "COUNTABLE印の所持数が上位の収集域へ入る。",
    scopeIntent: "catalog",
    primarySourceIntent: "title_collection_state",
    sourceStatusOriginal: "meta path未実装",
    collectionCredit: "NONCOUNT",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "分布TBD",
    productionReadinessOriginal: "meta基盤待ち",
    blockerNotes: "完全取得を意味しない。",
    fullClear: "EXEMPT_META",
  },
  {
    no: 96,
    themeNo: 18,
    theme: "収集・極め",
    displayName: "千印万来",
    provisionalKey: "v2.meta.thousand_marks",
    kind: "meta",
    groupKey: "collection_meta",
    seriesKey: "collection_meta",
    stage: 5,
    semanticSpec: "COUNTABLE印を十分多く持ち、かつ複数の異なるテーマへ広く足跡がある。",
    scopeIntent: "catalog",
    primarySourceIntent: "title_collection_state",
    sourceStatusOriginal: "meta path未実装",
    collectionCredit: "NONCOUNT",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "分布TBD",
    productionReadinessOriginal: "meta基盤待ち",
    blockerNotes: "万印皆伝とは別。高い取得数 + theme breadth。完全取得は不要。",
    fullClear: "EXEMPT_META",
  },
  {
    no: 97,
    themeNo: 18,
    theme: "収集・極め",
    displayName: "あと少しが遠い",
    provisionalKey: "v2.meta.so_close_so_far",
    kind: "meta",
    groupKey: "collection_meta",
    seriesKey: "collection_meta",
    stage: 6,
    semanticSpec: "そのfull-clear editionで必要な取得可能印のうち、未取得がごく少数だけ残っている。",
    scopeIntent: "catalog",
    primarySourceIntent: "title_collection_state",
    sourceStatusOriginal: "meta path未実装",
    collectionCredit: "NONCOUNT",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "full-clear manifest依存",
    productionReadinessOriginal: "meta基盤待ち",
    blockerNotes: "残数閾値はmanifest総数と取得分布から固定。",
    fullClear: "EXEMPT_META",
  },
  {
    no: 98,
    themeNo: 18,
    theme: "収集・極め",
    displayName: "万印皆伝",
    provisionalKey: "v2.meta.master_of_marks",
    kind: "meta",
    groupKey: "collection_meta",
    seriesKey: "collection_meta",
    stage: 7,
    semanticSpec: "そのfull-clear editionで取得可能な全required印を、例外なくすべて取得する。",
    scopeIntent: "catalog",
    primarySourceIntent: "title_collection_state",
    sourceStatusOriginal: "meta path未実装",
    collectionCredit: "NONCOUNT",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "full-clear 100%",
    productionReadinessOriginal: "meta基盤待ち",
    blockerNotes: "真の100% trophy。core極・招待・賭場・時間帯・role-aware・generic eventも、core_permanentとして収録するならrequired。",
    fullClear: "EXEMPT_META",
  },
  {
    no: 99,
    themeNo: 18,
    theme: "収集・極め",
    displayName: "一門皆伝",
    provisionalKey: "v2.meta.master_of_one_school",
    kind: "meta",
    groupKey: "series_mastery",
    seriesKey: null,
    stage: null,
    semanticSpec: "immutableなprogression seriesを一つ、最初に全取得する。",
    scopeIntent: "catalog",
    primarySourceIntent: "title_collection_state + progression manifest",
    sourceStatusOriginal: "meta path未実装",
    collectionCredit: "NONCOUNT",
    hidden: false,
    roleDependency: "none",
    thresholdIntent: "series manifest固定",
    productionReadinessOriginal: "meta基盤待ち",
    blockerNotes: "最初に皆伝したseriesをaward factsへ保存。万印皆伝とは独立。",
    fullClear: "EXEMPT_META",
  },
];
